# Generated by Django 6.0.5 on 2026-06-01 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_assignment_assigned_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanerapplication',
            name='origin',
            field=models.CharField(choices=[('cleaner_applied', 'Cleaner applied'), ('host_offered', 'Host offered')], default='cleaner_applied', max_length=20),
        ),
        migrations.CreateModel(
            name='FavouriteCleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_cleaners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('host', 'cleaner'), name='unique_favourite_cleaner_per_host')],
            },
        ),
    ]
