# Generated by Django 6.0.5 on 2026-07-22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("marketplace", "0008_lifecycle_constraints"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(name="Dispute", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("category", models.CharField(choices=[("safety", "Safety"), ("access", "Access"), ("quality", "Quality"), ("damage", "Damage"), ("privacy", "Privacy"), ("conduct", "Conduct"), ("schedule", "Schedule"), ("other", "Other")], max_length=24)),
            ("narrative", models.TextField()), ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], default="open", max_length=16)),
            ("filed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="filed_disputes", to=settings.AUTH_USER_MODEL)),
            ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="disputes", to="marketplace.cleaningjob")),
        ], options={"ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="DisputeUpdate", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("note", models.TextField()), ("status_after", models.CharField(blank=True, choices=[("open", "Open"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], max_length=16)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="dispute_updates", to=settings.AUTH_USER_MODEL)),
            ("dispute", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="updates", to="marketplace.dispute")),
        ], options={"ordering": ["created_at", "id"]}),
        migrations.CreateModel(name="JobIncident", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("incident_type", models.CharField(choices=[("no_show", "No-show"), ("attendance_failure", "Attendance failure")], max_length=32)), ("narrative", models.TextField()), ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)), ("severity", models.CharField(choices=[("standard", "Standard"), ("major", "Major"), ("critical", "Critical")], default="standard", max_length=16)),
            ("classified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="classified_job_incidents", to=settings.AUTH_USER_MODEL)), ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="marketplace.cleaningjob")), ("reported_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reported_job_incidents", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering": ["-created_at", "-id"]}),
        migrations.CreateModel(name="ReplacementRequest", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("expires_at", models.DateTimeField()), ("status", models.CharField(choices=[("pending_host_authorization", "Pending host authorization"), ("authorized", "Authorized"), ("declined", "Declined"), ("expired", "Expired"), ("withdrawn", "Withdrawn")], max_length=32)),
            ("authorized_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="authorized_replacement_requests", to=settings.AUTH_USER_MODEL)), ("incident", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="replacement_requests", to="marketplace.jobincident")), ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="replacement_requests", to=settings.AUTH_USER_MODEL)), ("source_job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="replacement_requests", to="marketplace.cleaningjob")), ("successor", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replacement_request", to="marketplace.cleaningjob")),
        ], options={"ordering": ["-created_at", "-id"], "constraints": [models.UniqueConstraint(condition=models.Q(("status__in", ["pending_host_authorization", "authorized"])), fields=("source_job",), name="uq_actionable_replacement_per_job")]}),
        migrations.CreateModel(name="RescheduleProposal", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("original_start", models.DateTimeField()), ("original_end", models.DateTimeField()), ("proposed_start", models.DateTimeField()), ("proposed_end", models.DateTimeField()), ("expires_at", models.DateTimeField()), ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired")], default="pending", max_length=16)), ("admin_authority_reference", models.CharField(blank=True, max_length=128)),
            ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reschedule_proposals", to="marketplace.cleaningjob")), ("proposed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reschedule_proposals", to=settings.AUTH_USER_MODEL)), ("responded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="responded_reschedule_proposals", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering": ["-created_at", "-id"], "constraints": [models.CheckConstraint(condition=models.Q(("proposed_end__gt", models.F("proposed_start"))), name="reschedule_end_after_start"), models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("job",), name="uq_pending_reschedule_per_job")]})
    ]
