# Generated by Django 6.0.5 on 2026-07-22 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_deduplication_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("email", "Email")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("retryable_failed", "Retryable failed"),
                            ("final_failed", "Final failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("final_failed_at", models.DateTimeField(blank=True, null=True)),
                ("provider_external_id", models.CharField(blank=True, max_length=255)),
                ("error_category", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_app_notification",
                to="notifications.notificationdelivery",
            ),
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("contract_version", models.PositiveSmallIntegerField(default=1)),
                ("language", models.CharField(default="bg", max_length=8)),
                ("occurrence_key", models.CharField(max_length=255)),
                (
                    "deduplication_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("destination", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source_entity_type", models.CharField(blank=True, max_length=64)),
                ("source_entity_id", models.CharField(blank=True, max_length=100)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="notifications.notificationevent",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_app_notification",
                to="notifications.notificationevent",
            ),
        ),
        migrations.CreateModel(
            name="OperatorNotificationAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_code",
                    models.CharField(
                        default="notification_delivery_final_failed", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_notification_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operator_alert",
                        to="notifications.notificationdelivery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("retryable_failed", "Retryable failed"),
                            ("final_failed", "Final failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="processing",
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_category", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("provider_external_id", models.CharField(blank=True, max_length=255)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="notifications.notificationdelivery",
                    ),
                ),
            ],
            options={
                "ordering": ["delivery_id", "attempt_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("delivery", "attempt_number"),
                        name="uq_notification_delivery_attempt_number",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="notif_event_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["recipient", "created_at"], name="notif_event_recipient_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "channel", "created_at"],
                name="notif_delivery_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="notif_delivery_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "channel"),
                name="uq_notification_delivery_event_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 0)),
                name="notification_delivery_attempt_count_nonnegative",
            ),
        ),
    ]
