# Generated by Django 6.0.5 on 2026-05-29 13:17

import django.core.validators
from django.db import migrations, models


def trim_cleaner_bios(apps, schema_editor):
    cleaner_profile = apps.get_model("accounts", "CleanerProfile")
    for profile in cleaner_profile.objects.exclude(bio="").only("id", "bio"):
        if len(profile.bio) > 1500:
            profile.bio = profile.bio[:1500]
            profile.save(update_fields=["bio"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_cleanerprofile_work_availability"),
    ]

    operations = [
        migrations.RunPython(trim_cleaner_bios, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cleanerprofile",
            name="bio",
            field=models.CharField(
                blank=True,
                max_length=1500,
                validators=[django.core.validators.MaxLengthValidator(1500)],
            ),
        ),
    ]
