# Generated by Django 6.0.5 on 2026-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_cleaner_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
