# Generated by Django 6.0.5 on 2026-06-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_bg', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('country_code', models.CharField(default='BG', max_length=2)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('default_zoom', models.PositiveSmallIntegerField(default=11)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['sort_order', 'name_bg'],
            },
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('name_bg', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('zone_type', models.CharField(default='district', max_length=50)),
                ('legacy_names', models.JSONField(blank=True, default=list)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.city')),
            ],
            options={
                'ordering': ['city__sort_order', 'sort_order', 'name_bg'],
            },
        ),
        migrations.CreateModel(
            name='ServiceZoneGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', models.JSONField()),
                ('simplified_geometry', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('source_license', models.CharField(blank=True, max_length=150)),
                ('source_url', models.URLField(blank=True)),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='locations.servicezone')),
            ],
            options={
                'verbose_name_plural': 'service zone geometries',
            },
        ),
        migrations.AddConstraint(
            model_name='servicezone',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_service_zone_per_city'),
        ),
    ]
