export type SofiaDistrict = {
  sourceId: string;
  id: `sofia:osm-${string}`;
  name: string;
};

export const SOFIA_DISTRICTS: readonly SofiaDistrict[] = [
  { sourceId: "1", id: "sofia:osm-1", name: "ж.к. Банишора" },
  { sourceId: "2", id: "sofia:osm-2", name: "кв. Модерно предградие" },
  { sourceId: "3", id: "sofia:osm-3", name: "ж.к. Хиподрума" },
  { sourceId: "4", id: "sofia:osm-4", name: "ж.к. Белите брези" },
  { sourceId: "5", id: "sofia:osm-5", name: "ж.к. Борово" },
  { sourceId: "6", id: "sofia:osm-6", name: "ж.к. Красно село" },
  { sourceId: "7", id: "sofia:osm-7", name: "ж.к. Гоце Делчев" },
  { sourceId: "8", id: "sofia:osm-8", name: "ж.к. Стрелбище" },
  { sourceId: "9", id: "sofia:osm-9", name: "ж.к. Иван Вазов" },
  { sourceId: "10", id: "sofia:osm-10", name: "кв. Крива река" },
  { sourceId: "11", id: "sofia:osm-11", name: "ж.к. Лагера" },
  { sourceId: "12", id: "sofia:osm-12", name: "ж.к. Люлин 1" },
  { sourceId: "13", id: "sofia:osm-13", name: "ж.к. Люлин 2" },
  { sourceId: "14", id: "sofia:osm-14", name: "ж.к. Люлин 3" },
  { sourceId: "15", id: "sofia:osm-15", name: "ж.к. Люлин 4" },
  { sourceId: "16", id: "sofia:osm-16", name: "ж.к. Люлин 5" },
  { sourceId: "17", id: "sofia:osm-17", name: "ж.к. Люлин 6" },
  { sourceId: "18", id: "sofia:osm-18", name: "ж.к. Люлин 7" },
  { sourceId: "19", id: "sofia:osm-19", name: "ж.к. Люлин - център" },
  { sourceId: "20", id: "sofia:osm-20", name: "ж.к. Люлин 8" },
  { sourceId: "21", id: "sofia:osm-21", name: "ж.к. Люлин 9" },
  { sourceId: "22", id: "sofia:osm-22", name: "ж.к. Люлин 10" },
  { sourceId: "23", id: "sofia:osm-23", name: "ж.к. Гевгелийски" },
  { sourceId: "24", id: "sofia:osm-24", name: "ж.к. Западен парк" },
  { sourceId: "25", id: "sofia:osm-25", name: "ж.к. Красна поляна 1" },
  { sourceId: "26", id: "sofia:osm-26", name: "ж.к. Илинден" },
  { sourceId: "27", id: "sofia:osm-27", name: "ж.к. Бъкстон" },
  { sourceId: "28", id: "sofia:osm-28", name: "ж.к. Разсадник Коньовица" },
  { sourceId: "29", id: "sofia:osm-29", name: "ж.к. Обеля 1" },
  { sourceId: "30", id: "sofia:osm-30", name: "кв. Обеля" },
  { sourceId: "31", id: "sofia:osm-31", name: "ж.к. Обеля 2" },
  { sourceId: "32", id: "sofia:osm-32", name: "ж.к. Връбница 1" },
  { sourceId: "33", id: "sofia:osm-33", name: "ж.к. Връбница 2" },
  { sourceId: "34", id: "sofia:osm-34", name: "ж.к. Надежда 3" },
  { sourceId: "35", id: "sofia:osm-35", name: "ж.к. Надежда 4" },
  { sourceId: "36", id: "sofia:osm-36", name: "ж.к. Надежда 1" },
  { sourceId: "37", id: "sofia:osm-37", name: "ж.к. Надежда 2" },
  { sourceId: "38", id: "sofia:osm-38", name: "ж.к. Лев Толстой" },
  { sourceId: "39", id: "sofia:osm-39", name: "ж.к. Света Троица" },
  { sourceId: "40", id: "sofia:osm-40", name: "ж.к. Фондови жилища" },
  { sourceId: "41", id: "sofia:osm-41", name: "ж.к. Сердика" },
  { sourceId: "42", id: "sofia:osm-42", name: "ж.к. Зона Б-5" },
  { sourceId: "43", id: "sofia:osm-43", name: "ж.к. Зона Б-19" },
  { sourceId: "44", id: "sofia:osm-44", name: "кв. Подуяне" },
  { sourceId: "45", id: "sofia:osm-45", name: "ж.к. Яворов" },
  { sourceId: "46", id: "sofia:osm-46", name: "кв. Хладилника" },
  { sourceId: "47", id: "sofia:osm-47", name: "кв. Кръстова вада" },
  { sourceId: "48", id: "sofia:osm-48", name: "ж.к. Дианабад" },
  { sourceId: "49", id: "sofia:osm-49", name: "ж.к. Изгрев" },
  { sourceId: "50", id: "sofia:osm-50", name: "ж.к. Изток" },
  { sourceId: "51", id: "sofia:osm-51", name: "НПЗ Дианабад" },
  { sourceId: "52", id: "sofia:osm-52", name: "Промишлена зона Хладилника" },
  { sourceId: "53", id: "sofia:osm-53", name: "м. Гърдова глава" },
  { sourceId: "54", id: "sofia:osm-54", name: "ж.к. Панорама Бояна" },
  { sourceId: "55", id: "sofia:osm-55", name: "ж.к. Зона Б-5-3" },
  { sourceId: "56", id: "sofia:osm-56", name: "ж.к. Градина" },
  { sourceId: "57", id: "sofia:osm-57", name: "кв. Витоша" },
  { sourceId: "58", id: "sofia:osm-58", name: "ж.к. Красна поляна 3" },
  { sourceId: "59", id: "sofia:osm-59", name: "ж.к. Красна поляна 2" },
  { sourceId: "60", id: "sofia:osm-60", name: "НПЗ Средец" },
  { sourceId: "61", id: "sofia:osm-61", name: "ж.к. Славия" },
  { sourceId: "62", id: "sofia:osm-62", name: "ж.к. Речен парк" },
  { sourceId: "63", id: "sofia:osm-63", name: "ж.к. Света Магдалена" },
  { sourceId: "64", id: "sofia:osm-64", name: "ж.к. Зона Б-18" },
  { sourceId: "65", id: "sofia:osm-65", name: "м. Група-Зоопарк" },
  { sourceId: "66", id: "sofia:osm-66", name: "ж.к. Лозенец" },
  { sourceId: "67", id: "sofia:osm-67", name: "ж.к. Младост 1" },
  { sourceId: "68", id: "sofia:osm-68", name: "ж.к. Дървеница" },
  { sourceId: "69", id: "sofia:osm-69", name: "ж.к. Младост 1А" },
  { sourceId: "70", id: "sofia:osm-70", name: "ж.к. Студентски град" },
  { sourceId: "71", id: "sofia:osm-71", name: "ж.к. Манастирски ливади - Б" },
  { sourceId: "72", id: "sofia:osm-72", name: "ж.к. Манастирски ливади" },
  { sourceId: "73", id: "sofia:osm-73", name: "ж.к. Захарна фабрика" },
  { sourceId: "74", id: "sofia:osm-74", name: "кв. Манастирски ливади" },
  { sourceId: "75", id: "sofia:osm-75", name: "ж.к. Южен парк" },
  { sourceId: "76", id: "sofia:osm-76", name: "ж.к. Триъгълника-Надежда" },
  { sourceId: "77", id: "sofia:osm-77", name: "Център" },
  { sourceId: "78", id: "sofia:osm-78", name: "кв. Карпузица" },
  { sourceId: "79", id: "sofia:osm-79", name: "ж.к. Свобода" },
  { sourceId: "80", id: "sofia:osm-80", name: "кв. Факултета" },
  { sourceId: "81", id: "sofia:osm-81", name: "ж.к. Малинова долина" },
  { sourceId: "82", id: "sofia:osm-82", name: "кв. Илиянци" },
  { sourceId: "83", id: "sofia:osm-83", name: "Промишлена зона Илиянци" },
  { sourceId: "84", id: "sofia:osm-84", name: "кв. Малинова долина" },
  { sourceId: "85", id: "sofia:osm-85", name: "БАН IV км." },
  { sourceId: "86", id: "sofia:osm-86", name: "кв. Бенковски" },
  { sourceId: "87", id: "sofia:osm-87", name: "Военна рампа" },
  { sourceId: "88", id: "sofia:osm-88", name: "кв. Орландовци" },
  { sourceId: "89", id: "sofia:osm-89", name: "НПЗ Хаджи Димитър" },
  { sourceId: "90", id: "sofia:osm-90", name: "кв. Васил Левски" },
  { sourceId: "91", id: "sofia:osm-91", name: "ж.к. Гео Милев" },
  { sourceId: "92", id: "sofia:osm-92", name: "ж.к. Младост 2" },
  { sourceId: "93", id: "sofia:osm-93", name: "ж.к. Младост 3" },
  { sourceId: "94", id: "sofia:osm-94", name: "ж.к. Младост 4" },
  { sourceId: "95", id: "sofia:osm-95", name: "кв. Враждебна" },
  { sourceId: "96", id: "sofia:osm-96", name: "ж.к. Левски зона В" },
  { sourceId: "97", id: "sofia:osm-97", name: "ж.к. Левски зона Г" },
  { sourceId: "98", id: "sofia:osm-98", name: "ж.к. Сухата река" },
  { sourceId: "99", id: "sofia:osm-99", name: "ж.к. Хаджи Димитър" },
  { sourceId: "100", id: "sofia:osm-100", name: "в.з. Американски колеж" },
  { sourceId: "101", id: "sofia:osm-101", name: "ж.к. Канала" },
  { sourceId: "102", id: "sofia:osm-102", name: "СПЗ Слатина" },
  { sourceId: "103", id: "sofia:osm-103", name: "кв. Христо Ботев" },
  { sourceId: "104", id: "sofia:osm-104", name: "ж.к. Христо Смирненски" },
  { sourceId: "105", id: "sofia:osm-105", name: "7-ми 11-ти километър" },
  { sourceId: "106", id: "sofia:osm-106", name: "кв. Полигона" },
  { sourceId: "107", id: "sofia:osm-107", name: "ж.к. Дружба" },
  { sourceId: "108", id: "sofia:osm-108", name: "м. Къро" },
  { sourceId: "109", id: "sofia:osm-109", name: "НПЗ Искър" },
  { sourceId: "110", id: "sofia:osm-110", name: "кв. Горубляне" },
  { sourceId: "111", id: "sofia:osm-111", name: "ж.к. Експериментален" },
  { sourceId: "112", id: "sofia:osm-112", name: "НПЗ Изток" },
  { sourceId: "113", id: "sofia:osm-113", name: "кв. Бояна" },
  { sourceId: "114", id: "sofia:osm-114", name: "в.з. Килиите" },
  { sourceId: "115", id: "sofia:osm-115", name: "в.з. Киноцентъра ІІІ част" },
  { sourceId: "116", id: "sofia:osm-116", name: "кв. Княжево" },
  { sourceId: "117", id: "sofia:osm-117", name: "м. Мала кория" },
  { sourceId: "118", id: "sofia:osm-118", name: "в.з. Могилата" },
  { sourceId: "119", id: "sofia:osm-119", name: "м. Национален киноцентър" },
  { sourceId: "120", id: "sofia:osm-120", name: "Резиденция Бояна" },
  { sourceId: "121", id: "sofia:osm-121", name: "кв. Симеоново" },
  { sourceId: "122", id: "sofia:osm-122", name: "м. Воденицата" },
  { sourceId: "123", id: "sofia:osm-123", name: "кв. Горна баня" },
  { sourceId: "124", id: "sofia:osm-124", name: "м. Подлозище" },
  { sourceId: "125", id: "sofia:osm-125", name: "ж.к. Фохар" },
  { sourceId: "126", id: "sofia:osm-126", name: "в.з. Горна баня" },
  { sourceId: "127", id: "sofia:osm-127", name: "кв. Овча купел" },
  { sourceId: "128", id: "sofia:osm-128", name: "ж.к. Овча купел" },
  { sourceId: "129", id: "sofia:osm-129", name: "м. Равнище" },
  { sourceId: "130", id: "sofia:osm-130", name: "м. Секулица" },
  { sourceId: "131", id: "sofia:osm-131", name: "кв. Суходол" },
  { sourceId: "132", id: "sofia:osm-132", name: "кв. Република" },
  { sourceId: "133", id: "sofia:osm-133", name: "Трънска махала" },
  { sourceId: "134", id: "sofia:osm-134", name: "кв. Филиповци" },
  { sourceId: "135", id: "sofia:osm-135", name: "ж.к. Филиповци" },
  { sourceId: "136", id: "sofia:osm-136", name: "ж.к. Синева" },
  { sourceId: "137", id: "sofia:osm-137", name: "ж.к. София парк" },
  { sourceId: "138", id: "sofia:osm-138", name: "кв. Драгалевци" },
  { sourceId: "139", id: "sofia:osm-139", name: "Макси комплекс Секвоя" },
  { sourceId: "140", id: "sofia:osm-140", name: "ж.к. Райна Княгиня" },
  { sourceId: "141", id: "sofia:osm-141", name: "СПЗ Модерно предградие" },
  { sourceId: "142", id: "sofia:osm-142", name: "Район Овча Купел" },
  { sourceId: "143", id: "sofia:osm-143", name: "Складова Зона" },
  { sourceId: "144", id: "sofia:osm-144", name: "м. Смърдана" },
];

export const SOFIA_DISTRICT_BY_SOURCE_ID = new Map(
  SOFIA_DISTRICTS.map((district) => [district.sourceId, district] as const),
);
